import type {
  CatalogArticle,
  CatalogSourceMeta,
} from "./catalogAnalysisTypes";

// =============================================================
// Catalogo demo Vallmec per "Analisi catalogo".
//
// In produzione l'analisi girerebbe sul catalogo reale del cliente
// (PDF listino / Catalogo ricambi, export gestionale, distinta BOM).
// Qui i dati sono intenzionalmente "sporchi" per dimostrare l'agente:
// duplicati tra fonti, obsoleti, sostituzioni, gap gestionale, prezzi
// mancanti e descrizioni incoerenti.
// =============================================================

export const CATALOG_SOURCES: CatalogSourceMeta[] = [
  {
    id: "listino-2026",
    label: "Listino ricambi 2026",
    fileName: "Listino_ricambi_Vallmec_2026.xlsx",
  },
  {
    id: "catalogo-vlm-2200",
    label: "Catalogo VLM-2200",
    fileName: "Catalogo_ricambi_Vallmec_VLM-2200.pdf",
  },
  {
    id: "db-vlm-2200",
    label: "Distinta DB VLM-2200 rev.C",
    fileName: "DB_VLM-2200_rev.C.xlsx",
  },
  {
    id: "gestionale",
    label: "Export gestionale",
    fileName: "Export_anagrafica_ricambi.csv",
  },
];

export const DEMO_CATALOG_ARTICLES: CatalogArticle[] = [
  // --- Cinghia: duplicato + sostituzione ---
  {
    id: "a-001",
    code: "VLM-400-009/2",
    description: "Cinghia dentata AT10 L=2250 h.25",
    sourceId: "listino-2026",
    location: "Foglio Spinta · riga 42",
    listPrice: 69.7,
    purchasePrice: 33.2,
    category: "trasmissione",
    inErp: true,
    erpDescription: "Cinghia dentata AT10 L=2250 h.25",
    erpPrice: 69.7,
    movements24m: 18,
    erpAvailable: true,
  },
  {
    id: "a-002",
    code: "VLM-400-009/2",
    description: "Cinghia AT10 2250×25 gruppo spinta",
    sourceId: "catalogo-vlm-2200",
    location: "Pag. 14 · gruppo spinta",
    listPrice: 69.7,
    purchasePrice: 33.2,
    category: "trasmissione",
    inErp: true,
    movements24m: 18,
    erpAvailable: true,
  },
  {
    id: "a-003",
    code: "VLM-400-009/1",
    description: "Cinghia dentata AT10 L=1950 h.25 rinforzata",
    sourceId: "listino-2026",
    location: "Foglio Spinta · riga 41",
    listPrice: 64.5,
    purchasePrice: 30.8,
    category: "trasmissione",
    inErp: true,
    erpDescription: "Cinghia AT10 L=1950 (VLM 1800)",
    erpPrice: 64.5,
    movements24m: 4,
    erpAvailable: true,
  },
  {
    id: "a-004",
    code: "VLM-400-009",
    description: "Cinghia dentata AT10 gruppo spinta (fuori produzione)",
    sourceId: "catalogo-vlm-2200",
    location: "Pag. 14 · nota storica",
    listPrice: null,
    purchasePrice: 28.0,
    category: "trasmissione",
    inErp: true,
    erpDescription: "Cinghia AT10 FP — non ordinabile",
    erpPrice: null,
    movements24m: 0,
    erpAvailable: false,
    obsoleteFlag: true,
  },

  // --- Ventose: obsoleto SI + descrizione incoerente ---
  {
    id: "a-010",
    code: "VLM-300-004",
    description: "Ventosa a soffietto D.50 NBR",
    sourceId: "listino-2026",
    location: "Foglio Formazione · riga 12",
    listPrice: 19.04,
    purchasePrice: 9.5,
    category: "pneumatica",
    inErp: true,
    erpDescription: "Ventosa soffietto Ø50 NBR Festo ESS-50-SN",
    erpPrice: 19.04,
    movements24m: 42,
    erpAvailable: true,
  },
  {
    id: "a-011",
    code: "VLM-300-004",
    description: "Ventosa soffietto 50 mm nitrile",
    sourceId: "db-vlm-2200",
    location: "Foglio Formazione · pos. 18",
    listPrice: 19.04,
    purchasePrice: 9.5,
    category: "pneumatica",
    inErp: true,
    movements24m: 42,
    erpAvailable: true,
  },
  {
    id: "a-012",
    code: "VLM-300-004-SI",
    description: "Ventosa silicone D.50 (solo VLM 1600 fino matr. 0654)",
    sourceId: "catalogo-vlm-2200",
    location: "Pag. 9 · note",
    listPrice: 22.0,
    purchasePrice: 11.0,
    category: "pneumatica",
    inErp: true,
    erpDescription: "Ventosa SI D50 — FP",
    erpPrice: 22.0,
    movements24m: 0,
    erpAvailable: false,
    obsoleteFlag: true,
  },

  // --- Fotocellula: prezzo gestionale divergente ---
  {
    id: "a-020",
    code: "VLM-200-040",
    description: "Fotocellula presenza prodotto E3Z-D62",
    sourceId: "listino-2026",
    location: "Foglio Alimentazione · riga 8",
    listPrice: 62.78,
    purchasePrice: 25.1,
    category: "elettrica",
    inErp: true,
    erpDescription: "Fotocellula E3Z-D62",
    erpPrice: 58.9,
    movements24m: 11,
    erpAvailable: true,
  },
  {
    id: "a-021",
    code: "VLM-200-040",
    description: "Sensore fotoelettrico presenza cartone Omron E3Z",
    sourceId: "catalogo-vlm-2200",
    location: "Pag. 6 · alimentazione",
    listPrice: 62.78,
    purchasePrice: 25.1,
    category: "elettrica",
    inErp: true,
    movements24m: 11,
    erpAvailable: true,
  },

  // --- Assente a gestionale ---
  {
    id: "a-030",
    code: "VLM-400-010",
    description: "Puleggia dentata AT10 z=32",
    sourceId: "db-vlm-2200",
    location: "Foglio Spinta · pos. 7",
    listPrice: 48.5,
    purchasePrice: 22.0,
    category: "trasmissione",
    inErp: false,
    movements24m: 0,
    erpAvailable: false,
  },
  {
    id: "a-031",
    code: "VLM-400-010",
    description: "Puleggia AT10 32 denti alluminio",
    sourceId: "catalogo-vlm-2200",
    location: "Pag. 14 · gruppo spinta",
    listPrice: 48.5,
    purchasePrice: 22.0,
    category: "trasmissione",
    inErp: false,
    movements24m: 0,
    erpAvailable: false,
  },

  // --- Prezzo mancante + categoria da proporre ---
  {
    id: "a-040",
    code: "VLM-200-002",
    description: "Tappeto modulare passo 25,4 acetalica Intralox 900",
    sourceId: "listino-2026",
    location: "Foglio Alimentazione · riga 3",
    listPrice: null,
    purchasePrice: 64.9,
    category: "meccanica",
    inErp: true,
    erpDescription: "Tappeto modulare 900 SERIES L=300",
    erpPrice: null,
    movements24m: 6,
    erpAvailable: true,
  },
  {
    id: "a-041",
    code: "VLM-NEW-088",
    description: "Rullo di contrasto poliuretano Ø80×300",
    sourceId: "db-vlm-2200",
    location: "Foglio Uscita · pos. 4",
    listPrice: null,
    purchasePrice: 41.0,
    category: null,
    inErp: false,
    movements24m: 0,
    erpAvailable: false,
  },

  // --- Sicurezza ---
  {
    id: "a-050",
    code: "VLM-100-031",
    description: "Serratura di sicurezza porta con RFID",
    sourceId: "listino-2026",
    location: "Foglio Sicurezza · riga 2",
    listPrice: 286.2,
    purchasePrice: 119.0,
    category: "sicurezza",
    inErp: true,
    erpDescription: "Serratura XCSDMR79M12 Schneider",
    erpPrice: 286.2,
    movements24m: 3,
    erpAvailable: true,
  },
  {
    id: "a-051",
    code: "VLM-100-031",
    description: "Blocco porta RFID XCSDMR79M12",
    sourceId: "db-vlm-2200",
    location: "Foglio Protezioni · pos. 1",
    listPrice: 286.2,
    purchasePrice: 119.0,
    category: "sicurezza",
    inErp: true,
    movements24m: 3,
    erpAvailable: true,
  },

  // --- Kit / cuscinetto ---
  {
    id: "a-060",
    code: "VLM-CU-6205",
    description: "Cuscinetto rigido a sfere 6205-2RS1",
    sourceId: "listino-2026",
    location: "Foglio Meccanica · riga 1",
    listPrice: 7.03,
    purchasePrice: 3.2,
    category: "meccanica",
    inErp: true,
    erpDescription: "Cuscinetto 6205 2RS",
    erpPrice: 7.03,
    movements24m: 55,
    erpAvailable: true,
  },
  {
    id: "a-061",
    code: "VLM-KIT-2000H",
    description: "Kit manutenzione 2.000 ore VLM 2200",
    sourceId: "listino-2026",
    location: "Foglio Kit · riga 1",
    listPrice: 278.8,
    purchasePrice: 155.0,
    category: "kit",
    inErp: true,
    erpDescription: "Kit 2000h VLM-2200",
    erpPrice: 278.8,
    movements24m: 9,
    erpAvailable: true,
  },

  // --- Finecorsa: solo catalogo, no ERP ---
  {
    id: "a-070",
    code: "VLM-400-030",
    description: "Sensore di finecorsa induttivo M12",
    sourceId: "catalogo-vlm-2200",
    location: "Pag. 15 · spinta",
    listPrice: 41.85,
    purchasePrice: 16.7,
    category: "elettrica",
    inErp: false,
    movements24m: 0,
    erpAvailable: false,
  },

  // --- Generatore vuoto ok ---
  {
    id: "a-080",
    code: "VLM-300-005",
    description: "Generatore di vuoto",
    sourceId: "listino-2026",
    location: "Foglio Formazione · riga 14",
    listPrice: 84.1,
    purchasePrice: 42.0,
    category: "pneumatica",
    inErp: true,
    erpDescription: "Generatore di vuoto",
    erpPrice: 84.1,
    movements24m: 7,
    erpAvailable: true,
  },

  // --- Obsoleto non movimentato ---
  {
    id: "a-090",
    code: "VLM-1600-VENT-OLD",
    description: "Gruppo ventose VLM 1600 legacy",
    sourceId: "gestionale",
    location: "Anagrafica · stato FP",
    listPrice: 120.0,
    purchasePrice: 55.0,
    category: "pneumatica",
    inErp: true,
    erpDescription: "Gruppo ventose VLM1600 — FP",
    erpPrice: 120.0,
    movements24m: 0,
    erpAvailable: false,
    obsoleteFlag: true,
  },

  // --- Sostituzione pattino ---
  {
    id: "a-100",
    code: "VLM-400-022",
    description: "Pattino di spinta in POM",
    sourceId: "listino-2026",
    location: "Foglio Spinta · riga 48",
    listPrice: 102.4,
    purchasePrice: 48.0,
    category: "meccanica",
    inErp: true,
    erpDescription: "Pattino spinta POM bianco",
    erpPrice: 102.4,
    movements24m: 8,
    erpAvailable: true,
  },
  {
    id: "a-101",
    code: "VLM-400-022A",
    description: "Pattino di spinta POM rinforzato (rev.A)",
    sourceId: "db-vlm-2200",
    location: "Foglio Spinta · pos. 12",
    listPrice: 114.0,
    purchasePrice: 52.0,
    category: "meccanica",
    inErp: true,
    erpDescription: "Pattino spinta POM rev.A",
    erpPrice: 114.0,
    movements24m: 2,
    erpAvailable: true,
  },

  // --- Prezzo mancante kit ---
  {
    id: "a-110",
    code: "VLM-KIT-8000H",
    description: "Kit manutenzione 8.000 ore VLM 2200",
    sourceId: "listino-2026",
    location: "Foglio Kit · riga 2",
    listPrice: null,
    purchasePrice: 470.0,
    category: "kit",
    inErp: true,
    erpDescription: "Kit 8000h VLM-2200",
    erpPrice: null,
    movements24m: 1,
    erpAvailable: true,
  },

  // --- Cuscinetto descrizione ERP diversa (stesso codice) ---
  {
    id: "a-120",
    code: "VLM-200-011",
    description: "Supporto flangiato UCF 205",
    sourceId: "listino-2026",
    location: "Foglio Alimentazione · riga 5",
    listPrice: 18.71,
    purchasePrice: 8.5,
    category: "meccanica",
    inErp: true,
    erpDescription: "Supporto UCF205 con cuscinetto",
    erpPrice: 18.71,
    movements24m: 14,
    erpAvailable: true,
  },
];

export function articlesById(
  articles: CatalogArticle[] = DEMO_CATALOG_ARTICLES
): Map<string, CatalogArticle> {
  return new Map(articles.map((a) => [a.id, a]));
}
